upload:
  upload_path: /tmp/pfdr/incoming/
  rsync_point: localhost:incoming
  storage_path: /tmp/pfdr/storage/
validation:
  external:
    audio: "bin/validate_audio.sh"
    video: "bin/validate_video.pl"
  bagger_profile:
    digital: "spec/support/fixtures/test-profile.json"
checkpoint:
  database:
    adapter: sqlite
    database: db/checkpoint_test.sqlite3
keycard:
  database:
    url: "sqlite://db/keycard_test.sqlite3"
  access: proxy

