allow_impersonation: true

upload:
  upload_path: data/incoming
  rsync_point: localhost:data/incoming
  storage_path: data/storage
validation:
  # These files noop with exit code 0 under normal test, but delegate to their
  # corresponding files in bin when RUN_INTEGRATION is 1.
  external:
    audio: "spec/support/bin/validate_audio.sh"
    bentleyaudio: "spec/support/bin/validate_bentleyaudio.sh"
    video: "spec/support/bin/validate_video.sh"
  bagger_profile:
    digital: "spec/support/fixtures/test-profile.json"
checkpoint:
  database:
    adapter: sqlite
    database: db/checkpoint_test.sqlite3
keycard:
  database:
    url: "sqlite://db/keycard_test.sqlite3"
  access: proxy

